[package]
name = "protowirers"
version = "0.1.0"
authors = ["blck-snwmn <whitesnowmancreator@gmail.com>"]
edition = "2018"

[workspace]
members = ["impl"]


[[test]]
name = "tests"
path = "tests/tests.rs"

[dependencies]
byteorder = "1"
syn={version = "1.0", features=["full"]}
proc-macro2="1.0"
quote = "1.0"
thiserror = "1.0"
anyhow = "1.0"
trybuild = { version = "1.0.19", features = ["diff"] }

protowirers-impl={version="0.1.0", path = "impl"}
